name: GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: carlinhoscamilo/trilho:latest
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE: trilho 
      REGION: us-central1 
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # GCP Auth
    - name: GCP Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_ACCOUNT_KEY }}

    # Build image
    - name: Build the Docker image
      run: docker build -t $IMAGE .

    # Auth Docker hub
    - name: Docker Hub Auth
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push image to container registry
    - name: Push image
      run: docker push $IMAGE

    # Deploy
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: $SERVICE
        region: $REGION
        image: $IMAGE
        env_vars: |
          DB_CONN=${{ secrets.DB_CONN }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          API_SECRET=${{ secrets.API_SECRET }}  

