name: GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Setup GCP Account
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/trilho:latest
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # GCP Auth
    - name: GCP Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_ACCOUNT_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Configure Docker on GCP
    - name: Configure Docker on GCP
      run: gcloud auth configure-docker --quiet

    # Build image
    - name: Build the Docker image
      run: docker build -t $IMAGE .
    
    # Push image to container registry
    - name: Push image
      run: docker push $IMAGE

    # Deploy on Cloud Run
    - name: Deploy on Cloud Run
      run: gcloud run deploy trilho-backend \
            --image $IMAGE --region us-central1 \
            --memory 128Mi --min-instances 0 --max-instances 1 \
            --port 80 --allow-unauthenticated \
            --set-env-vars "DB_USER=${{ secrets.DB_USER }}" \
            --set-env-vars "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            --set-env-vars "DB_HOST=${{ secrets.DB_HOST }}" \
            --set-env-vars "DB_PORT=${{ secrets.DB_PORT }}" \
            --set-env-vars "DB_NAME=${{ secrets.DB_NAME }}" \
            --set-env-vars "API_SECRET=${{ secrets.API_SECRET }}"
