name: GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Setup GCP Account
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: gcr.io/$({ secrets.GCP_PROJECT_ID })/trilho:latest
    steps:
    # Checkout
    - name: Checkout
    - uses: actions/checkout@v3

    # GCP Login
    - name: Login
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service-account-key: $({ secrets.GCP_ACCOUNT_KEY })
        project-id: $({ secrets.GCP_PROJECT_ID })

    # Configure Docker on GCP
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    # Build image
    - name: Build the Docker image
      run: docker build -t $IMAGE .
    
    # Push image to container registry
    - name: Push image
      run: docker push $IMAGE

    # Deploy on Cloud Run
    - name: Deploy App
      run: gcloud run deploy trilho-backend \
            --image $IMAGE --region us-central1 \
            --memory 128Mi --min-instances 0 --max-instances 1 \
            --port 80 --allow-unauthenticated \
            --set-env-vars=[\
                DB_USER=$({ secrets.DB_USER }),\
                DB_PASSWORD$({ secrets.DB_PASSWORD }),\
                DB_HOST$({ secrets.DB_HOST }).freesqldatabase.com,\
                DB_PORT$({ secrets.DB_PORT }),\
                DB_NAME$({ secrets.DB_NAME }),\
                API_SECRET$({ secrets.API_SECRET })]
